services:
    full_calendar.service.serializer:
        class: Toiba\FullCalendarBundle\Service\Serializer
        public: false

    full_calendar.service.calendar:
        class: Toiba\FullCalendarBundle\Service\Calendar
        arguments:
            - "@full_calendar.service.serializer"
            - "@event_dispatcher"
